import React from 'react';
import { View, Text, StyleSheet, Image, ScrollView, TouchableOpacity } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LineChart, Grid } from 'react-native-svg-charts';

export default function DeviceDetailsScreen({ route, navigation }) {
  const { name, number, image } = route.params || {};
  const liveData = [50, 120, 100, 90, 150, 130, 160, 110, 140];
  const monthData = [60, 100, 120, 150, 200, 180, 190];

  return (
    <ScrollView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Ionicons name="arrow-back" size={24} color="#000" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>{name}</Text>
        <View style={{ width: 24 }} />
      </View>

      {/* Diagram */}
      <Image source={require('../assets/diagram.png')} style={styles.diagram} resizeMode="contain" />

      {/* Device image */}
      <Image source={image} style={styles.deviceImage} resizeMode="cover" />

      {/* Solar Usage Card */}
      <View style={styles.usageCard}>
        <Text style={styles.usageValue}>30.276KWh</Text>
        <Text style={styles.usageLabel}>Solar Power Usage</Text>
        <View style={styles.progressBar}>
          <View style={[styles.progressFill, { width: '40%' }]} /> 
        </View>
        <Text style={styles.usagePercent}>40%</Text>
      </View>

      {/* Stats Row */}
      <View style={styles.statsRow}>
        <View style={styles.statBox}>
          <Ionicons name="sunny-outline" size={24} color="#000" />
          <Text style={styles.statValue}>36.2 Kwh</Text>
          <Text style={styles.statLabel}>Total energy</Text>
        </View>
        <View style={styles.statBox}>
          <Ionicons name="flash-outline" size={24} color="#000" />
          <Text style={styles.statValue}>28.2 Kwh</Text>
          <Text style={styles.statLabel}>Consumed</Text>
        </View>
      </View>

      <View style={styles.statsRow}>
        <View style={styles.statBox}>
          <Ionicons name="battery-full-outline" size={24} color="#000" />
          <Text style={styles.statValue}>42.0 Kwh</Text>
          <Text style={styles.statLabel}>Capacity</Text>
        </View>
        <View style={styles.statBox}>
          <Ionicons name="leaf-outline" size={24} color="#000" />
          <Text style={styles.statValue}>28.2 Kwh</Text>
          <Text style={styles.statLabel}>CO₂ Reduction</Text>
        </View>
      </View>

      {/* Live Chart */}
      <View style={styles.chartCard}>
        <Text style={styles.chartTitle}>Electricity generated by solar</Text>
        <Text style={styles.chartSub}>140.65KWh • Live</Text>
        <LineChart
          style={{ height: 150 }}
          data={liveData}
          svg={{ stroke: '#4CAF50', strokeWidth: 2 }}
          contentInset={{ top: 20, bottom: 20 }}
        >
          <Grid />
        </LineChart>
      </View>

      {/* Monthly Chart */}
      <View style={styles.chartCard}>
        <Text style={styles.chartTitle}>Energy generated</Text>
        <Text style={styles.chartSub}>30.276KWh • +2 131Wh (14%)</Text>
        <LineChart
          style={{ height: 150 }}
          data={monthData}
          svg={{ stroke: '#4CAF50', strokeWidth: 2 }}
          contentInset={{ top: 20, bottom: 20 }}
        >
          <Grid />
        </LineChart>
        {/* Summary */}
        <View style={styles.summaryRow}>
          <Text>150KWh Today</Text>
          <Text>165KWh This month</Text>
          <Text>398KWh All time</Text>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFE4E1' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    justifyContent: 'space-between',
  },
  headerTitle: { fontSize: 18, fontWeight: 'bold' },
  diagram: { width: '100%', height: 120, marginVertical: 10 },
  house: { width: '100%', height: 200 },
  usageCard: {
    backgroundColor: '#fff',
    margin: 15,
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  usageValue: { fontSize: 20, fontWeight: 'bold' },
  usageLabel: { fontSize: 14, color: '#555' },
  progressBar: {
    width: '100%',
    height: 6,
    backgroundColor: '#eee',
    borderRadius: 3,
    marginTop: 8,
  },
  progressFill: {
    height: 6,
    backgroundColor: '#4CAF50',
    borderRadius: 3,
  },
  usagePercent: { marginTop: 5, color: '#4CAF50', fontWeight: 'bold' },
  statsRow: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 10 },
  statBox: {
    backgroundColor: '#fff',
    flex: 0.45,
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  statValue: { fontSize: 16, fontWeight: 'bold', marginTop: 5 },
  statLabel: { fontSize: 12, color: '#555' },
  chartCard: {
    backgroundColor: '#fff',
    margin: 15,
    padding: 15,
    borderRadius: 12,
  },
  chartTitle: { fontSize: 16, fontWeight: 'bold' },
  chartSub: { fontSize: 12, color: '#555', marginBottom: 8 },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingTop: 8,
  },
});